<?php

namespace GoMobility\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends EntityRepository
{
    
     public function getLast3Actualites()
    {
    	return $this->createQueryBuilder('b')
              ->orderBy('b.date', 'DESC')
              ->setFirstResult(0)
              ->setMaxResults(3)
              ->getQuery()
              ->getResult();
    }
    
    
    
    
    
}
