<?php

namespace GoMobility\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function getAllMessages()
    {
        return $this->createQueryBuilder('a')
              ->orderBy('a.date', 'DESC')
              ->getQuery()
              ->getResult();
    }

	public function getReceived()
    {
        return $this->createQueryBuilder('a')
              ->where('a.type = :type')
              ->setParameter('type', 'reçu')        
              ->orderBy('a.date', 'DESC')         
              ->getQuery()
              ->getResult();
    }

    public function getSent()
    {
        return $this->createQueryBuilder('a')
              ->where('a.type = :type')
              ->setParameter('type', 'envoyé')        
              ->orderBy('a.date', 'DESC')         
              ->getQuery()
              ->getResult();
    }
}
