<?php

namespace GoMobility\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EcoactorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoactorRepository extends EntityRepository
{
	
    public function getExperiences()
    {
        return $this->createQueryBuilder('a')
              ->where('a.status = :status')
              ->setParameter('status', 'publié')        
              ->orderBy('a.date', 'DESC')         
              ->getQuery()
              ->getResult();
    }

    public function getTenExperience()
    {
      return $this->createQueryBuilder('b')
              ->orderBy('b.date', 'DESC')
              ->setFirstResult(0)
              ->setMaxResults(10)
              ->getQuery()
              ->getResult();
    }

    public function getLastExperience()
    {
    	return $this->createQueryBuilder('b')
              ->orderBy('b.date', 'DESC')
              ->setFirstResult(0)
              ->setMaxResults(1)
              ->getQuery()
              ->getResult();
    }

    public function getEcoactor()
    {
        return $this->createQueryBuilder('a')
              ->orderBy('a.date', 'DESC')
              ->getQuery()
              ->getResult();
    }

    public function getBestEcoactor()
    {
        return $this->createQueryBuilder('a')
              ->orderBy('a.ges', 'ASC')
              ->getQuery()
              ->getResult();
    }

    public function getTheBestEcoactor()
    {
        return $this->createQueryBuilder('a')
              ->orderBy('a.ges', 'ASC')
              ->setFirstResult(0)
              ->setMaxResults(1)
              ->getQuery()
              ->getArrayResult();
    }

    public function getUnpublish()
    {
        return $this->createQueryBuilder('a')
              ->where('a.status = :status')
              ->setParameter('status', 'non publié')        
              ->orderBy('a.date', 'DESC')         
              ->getQuery()
              ->getResult();
    }
}
